export const ACTIONS={
  ADD_CAMPGROUND:"ADD_CAMPGROUND",
  REMOVE_CAMPGROUND:"REMOVE_CAMPGROUND",
  SELECT_CHECK_IN:"SELECT_CHECK_IN_DATE",
  SELECT_CHECK_OUT:"SELECT_CHECK_OUT_DATE",
  SELECT_EQUIPMENT:"SELECT_EQUIPMENT",
  UPDATE_OPTIONS:"UPDATE_OPTIONS",
  UPDATE_STEP:"UPDATE_CURRENT_STEP",
  SELECT_DATES:"SELECT_DATES"
}