export const ACTIONS={
  ADD_CAMPGROUND:"ADD_CAMPGROUND",
  REMOVE_CAMPGROUND:"REMOVE_CAMPGROUND",
  SELECT_DATE:"SELECT_DATE",
  SELECT_EQUIPMENT:"SELECT_EQUIPMENT",
  UPDATE_OPTIONS:"UPDATE_OPTIONS",
  UPDATE_STEP:"UPDATE_CURRENT_STEP"
}